version: '3.7'

services:

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - mysql_vol:/var/lib/mysql
    networks:
      - inception_network
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    networks:
      - inception_network
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception_network
    restart: on-failure

volumes:
  mysql_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/edos-san/data/mysql
      o: bind
    name: mysql_vol
  
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/edos-san/data/wordpress
      o: bind
    name: wordpress_vol

networks:
  inception_network: