CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'edos-san'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON wordpress.* TO 'edos-san'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';